project:
  type: website

website:
  title: "Explore relationships between life expectancy and socio-economic factors"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: sources.qmd
        text: Sources


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



